#!/bin/bash

#Scripts
cd /workspace/stable-diffusion-webui/scripts

if [ -f /workspace/stable-diffusion-webui/scripts/txt2img2img.py ]; then echo "Skipping"; else read -p "Do you want to install the txt2img2img script? (Y/N): " answer; if [ "$answer" = "Y" ]; then git clone --depth 1 --single-branch https://github.com/ThereforeGames/txt2img2img /workspace/stable-diffusion-webui; elif [ "$answer" = "N" ]; then echo "Skipping"; else for i in {1..2}; do read -p "Invalid response. Do you want to install the txt2img2img script? (Y/N): " answer; if [ "$answer" = "Y" ]; then git clone --depth 1 --single-branch https://github.com/ThereforeGames/txt2img2img /workspace/stable-diffusion-webui; break; elif [ "$answer" = "N" ]; then echo "Skipping"; break; fi; done; if [ "$answer" != "Y" ] && [ "$answer" != "N" ]; then echo "Skipping"; fi; fi; fi

if [ -f /workspace/stable-diffusion-webui/scripts/improved_prompt_matrix.py ]; then echo "Skipping"; else read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || echo "Skipping")); fi
# if [ -f /workspace/stable-diffusion-webui/scripts/improved_prompt_matrix.py ]; then echo "Skipping"; else read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the improved_prompt_matrix script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/ArrowM/auto1111-improved-prompt-matrix/blob/main/improved_prompt_matrix.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/videos.py ]; then echo "Skipping"; else read -p "Do you want to install the videos script? (Y/N): " answer && { ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/memes-forever/Stable-diffusion-webui-video/blob/main/videos.py) || [ "$answer" = "N" ]; } || { echo "Please enter Y or N" && read -p "Do you want to install the videos script? (Y/N): " answer && { ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/memes-forever/Stable-diffusion-webui-video/blob/main/videos.py) || [ "$answer" = "N" ]; } || echo "Skipping"; }; fi
# if [ -f /workspace/stable-diffusion-webui/scripts/videos.py ]; then echo "Skipping"; else read -p "Do you want to install the videos script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/memes-forever/Stable-diffusion-webui-video/blob/main/videos.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the videos script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/memes-forever/Stable-diffusion-webui-video/blob/main/videos.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the videos script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/memes-forever/Stable-diffusion-webui-video/blob/main/videos.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ ! -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then while true; do read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py && break || [ "$answer" = "N" ]) && break || echo "Please enter Y or N"; done; fi
# if [ ! -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then while true; do read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py && break || [ "$answer" = "N" ]) && break || echo "Please enter Y or N"; done; fi
# if [ ! -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then while true; do read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py && break || [ "$answer" = "N" ]) && break || echo "Please enter Y or N"; done; fi# if [ -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then echo "Skipping"; else while true; do read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py && break || [ "$answer" = "N" ] && break) || echo "Please enter Y or N"; done; fi
# if [ -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then echo "Skipping"; else read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi
# if [ -f /workspace/stable-diffusion-webui/scripts/animation.py ]; then echo "Skipping"; else read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the animation script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Animator-Anon/Animator/blob/main/animation.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/alternate_sampler_noise_schedules.py ]; then echo "Skipping"; else read -p "Do you want to install the alternate_sampler_noise_schedules script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://gist.githubusercontent.com/dfaker/f88aa62e3a14b559fe4e5f6b345db664/raw/791dabfa0ab26399aa2635bcbc1cf6267aa4ffc2/alternate_sampler_noise_schedules.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the alternate_sampler_noise_schedules script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://gist.githubusercontent.com/dfaker/f88aa62e3a14b559fe4e5f6b345db664/raw/791dabfa0ab26399aa2635bcbc1cf6267aa4ffc2/alternate_sampler_noise_schedules.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the alternate_sampler_noise_schedules script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://gist.githubusercontent.com/dfaker/f88aa62e3a14b559fe4e5f6b345db664/raw/791dabfa0ab26399aa2635bcbc1cf6267aa4ffc2/alternate_sampler_noise_schedules.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/vid2vid.py ]; then echo "Skipping"; else read -p "Do you want to install the vid2vid script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the vid2vid script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the vid2vid script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Filarius/stable-diffusion-webui/blob/master/scripts/vid2vid.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/txt2vectorgfx.py ]; then echo "Skipping"; else read -p "Do you want to install the txt2vectorgfx script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/GeorgLegato/Txt2Vectorgraphics/blob/main/txt2vectorgfx.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the txt2vectorgfx script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/GeorgLegato/Txt2Vectorgraphics/blob/main/txt2vectorgfx.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the txt2vectorgfx script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/GeorgLegato/Txt2Vectorgraphics/blob/main/txt2vectorgfx.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi
# Because the above script needs potrace the next line installs and adds it to requirements.txt so it should remain persistent when the pod is restarted.
if [ -f /workspace/stable-diffusion-webui/scripts/txt2vectorgfx.py ]; then pip install potrace || : && echo "potrace" >> /workspace/stable-diffusion-webui/requirements.txt; else :; fi

if [ -f /workspace/stable-diffusion-webui/scripts/interpolate.py ]; then echo "Skipping"; else read -p "Do you want to install the interpolate script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/interpolate.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the interpolate script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/interpolate.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the interpolate script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/interpolate.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/loopback_superimpose.py ]; then echo "Skipping"; else read -p "Do you want to install the loopback_superimpose script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/loopback_superimpose.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the loopback_superimpose script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/loopback_superimpose.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the loopback_superimpose script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/DiceOwl/StableDiffusionStuff/blob/main/loopback_superimpose.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/img2tiles.py ]; then echo "Skipping"; else read -p "Do you want to install the img2tiles script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/arcanite24/img2tiles/blob/master/img2tiles.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the img2tiles script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/arcanite24/img2tiles/blob/master/img2tiles.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the img2tiles script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/arcanite24/img2tiles/blob/master/img2tiles.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/img2mosaic.py ]; then echo "Skipping"; else read -p "Do you want to install the img2mosaic script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/1ort/img2mosaic/blob/main/img2mosaic.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the img2mosaic script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/1ort/img2mosaic/blob/main/img2mosaic.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the img2mosaic script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/1ort/img2mosaic/blob/main/img2mosaic.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi

if [ -f /workspace/stable-diffusion-webui/scripts/test_my_prompt_custom_script.py ]; then echo "Skipping"; else read -p "Do you want to install the test_my_prompt_custom_script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Extraltodeus/test_my_prompt/blob/main/test_my_prompt/scripts/test_my_prompt_custom_script.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the test_my_prompt_custom_script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Extraltodeus/test_my_prompt/blob/main/test_my_prompt/scripts/test_my_prompt_custom_script.py || [ "$answer" = "N" ]) || (echo "Please enter Y or N" && read -p "Do you want to install the test_my_prompt_custom_script? (Y/N): " answer && ([ "$answer" = "Y" ] && wget -P /workspace/stable-diffusion-webui/scripts https://github.com/Extraltodeus/test_my_prompt/blob/main/test_my_prompt/scripts/test_my_prompt_custom_script.py || [ "$answer" = "N" ]) || echo "Skipping"))); fi
